# Generated by Django 4.2.21 on 2026-01-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('JPY', 'Japanese Yen (¥)'), ('CNY', 'Chinese Yuan (¥)'), ('INR', 'Indian Rupee (₹)'), ('CAD', 'Canadian Dollar ($)'), ('AUD', 'Australian Dollar ($)'), ('CHF', 'Swiss Franc (Fr)'), ('MXN', 'Mexican Peso ($)'), ('BRL', 'Brazilian Real (R$)'), ('ZAR', 'South African Rand (R)'), ('SGD', 'Singapore Dollar ($)'), ('HKD', 'Hong Kong Dollar ($)'), ('NZD', 'New Zealand Dollar ($)'), ('SEK', 'Swedish Krona (kr)'), ('NOK', 'Norwegian Krone (kr)'), ('KRW', 'South Korean Won (₩)'), ('TRY', 'Turkish Lira (₺)'), ('RUB', 'Russian Ruble (₽)'), ('AED', 'UAE Dirham (د.إ)'), ('THB', 'Thai Baht (฿)'), ('PLN', 'Polish Zloty (zł)'), ('DKK', 'Danish Krone (kr)')], default='USD', help_text='Currency for this trip', max_length=3),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_currency',
            field=models.CharField(choices=[('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('JPY', 'Japanese Yen (¥)'), ('CNY', 'Chinese Yuan (¥)'), ('INR', 'Indian Rupee (₹)'), ('CAD', 'Canadian Dollar ($)'), ('AUD', 'Australian Dollar ($)'), ('CHF', 'Swiss Franc (Fr)'), ('MXN', 'Mexican Peso ($)'), ('BRL', 'Brazilian Real (R$)'), ('ZAR', 'South African Rand (R)'), ('SGD', 'Singapore Dollar ($)'), ('HKD', 'Hong Kong Dollar ($)'), ('NZD', 'New Zealand Dollar ($)'), ('SEK', 'Swedish Krona (kr)'), ('NOK', 'Norwegian Krone (kr)'), ('KRW', 'South Korean Won (₩)'), ('TRY', 'Turkish Lira (₺)'), ('RUB', 'Russian Ruble (₽)'), ('AED', 'UAE Dirham (د.إ)'), ('THB', 'Thai Baht (฿)'), ('PLN', 'Polish Zloty (zł)'), ('DKK', 'Danish Krone (kr)')], default='USD', max_length=3),
        ),
    ]
